[package]
name = "helvum"
version = "0.6.2"
authors = ["Tom Wagner <tom.a.wagner@protonmail.com>", "Naveen Prashanth <gnpaone@gmail.com>"]
edition = "2021"
rust-version = "1.94"
license = "GPL-3.0-only"
description = "A GTK patchbay for pipewire"
repository = "https://gitlab.freedesktop.org/pipewire/helvum"
readme = "README.md"
keywords = ["pipewire", "gtk", "patchbay", "gui", "utility"]
categories = ["gui", "multimedia"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pipewire  = "0.9.2"
libspa    = "0.9.2"
async-channel = "2.5.0"
adw = { version = "0.9.1", package = "libadwaita", features = ["v1_7", "gtk_v4_18"] }
glib = { version = "0.22.7", features = ["log", "v2_84"] }
gtk4 = "0.11.3"

log = "0.4.29"

libc = "0.2.186"
futures-util = "0.3.32"
